version = "2"

[com]
protocol = "uds"
socket_path = "/tmp/termusic.socket"
port = 50101
address = "::1"

[player]
music_dirs = ["/home/nemesis/Music"]
library_scan_depth = 10
loop_mode = "playlist"
volume = 30
speed = 10
gapless = true
use_mediacontrols = true
set_discord_status = true
random_track_quantity = 20
random_album_min_quantity = 5
backend = "rusty"

[player.remember_position]
music = "no"
podcast = "yes"

[player.seek_step]
short_tracks = 5
long_tracks = 30

[podcast]
concurrent_downloads_max = 3
max_download_retries = 3
download_dir = "/home/nemesis/Music/podcast"

[backends.rusty]
soundtouch = true
file_buffer_size = "4.0 MiB"
decoded_buffer_size = "750.0 KiB"
